[package]
name = "tiktoken"
version = "0.7.0"
edition = "2021"
rust-version = "1.57.0"

[lib]
name = "_tiktoken"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }

# tiktoken dependencies
fancy-regex = "0.11.0"
regex = "1.8.3"
rustc-hash = "1.1.0"
bstr = "1.5.0"
# cli dependencies
tui-textarea = "0.4.0"
crossterm = "0.27.0"
ratatui = "0.26.3"

